name: opti_job_app
description: Nueva versiÃ³n Flutter del frontend de InfoJobs
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  uuid: ^4.5.2
  flutter_bloc: ^9.1.1
  camera: ^0.11.3
  video_player: ^2.8.2
  video_compress: ^3.1.2
  bloc: ^9.1.0
  cross_file: ^0.3.5
  go_router: ^17.0.0
  flutter_slidable: ^4.0.3
  flutter_localization: ^0.3.3
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  table_calendar: ^3.1.1
  intl: ^0.20.2
  excel: ^4.0.6
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  image_picker: ^1.2.1
  file_picker: ^10.3.8
  crypto: ^3.0.6
  archive: ^3.6.1
  path_provider: ^2.1.5
  pdf: ^3.11.0
  share_plus: ^12.0.1
  url_launcher: ^6.3.0
  equatable: ^2.0.7
  firebase_ai: ^3.6.1
  firebase_app_check: ^0.4.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0
  build_runner: ^2.10.4
  mocktail: ^1.0.4
  fake_cloud_firestore: ^4.0.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo_app.png
  android: true
  ios: true
  web: false
  android_gravity: center

  android_12:
    image: assets/logo_app.png
    icon_background_color: "#ffffff"

flutter:
  generate: true
  uses-material-design: true
  

    
