name: infojobs_flutter_app
description: Nueva versiÃ³n Flutter del frontend de InfoJobs
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  uuid: ^4.5.2
  flutter_bloc: ^9.1.1
  go_router: ^17.0.0
  flutter_slidable: ^3.1.0
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  table_calendar: ^3.1.1
  intl: ^0.20.2
  excel: ^4.0.6
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  get_it: ^7.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.1.3
  image_picker: ^1.2.1
  crypto: ^3.0.6
  path_provider: ^2.1.5
  pdf: ^3.11.0
  share_plus: ^10.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0
  build_runner: ^2.10.4
  mocktail: ^1.0.4
  fake_cloud_firestore: ^3.1.0
  http: ^1.2.2

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo_app.png
  android: true
  ios: true
  web: false
  android_gravity: center

  android_12:
    image: assets/logo_app.png
    icon_background_color: "#ffffff"

flutter:
  uses-material-design: true
  

    
