name: infojobs_flutter_backend
description: Backend reimplementado en Dart para InfoJobs
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.2.0
  postgres: ^3.2.0
  dotenv: ^4.2.0
  dart_jsonwebtoken: ^2.7.1
  bcrypt: ^1.1.3
  logging: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
